using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using EssaLab.StronglyTypedIds.Convertors.EFCore.Common.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EssaLab.StronglyTypedIds.Convertors.EFCore;

[Generator]
public sealed class EfConverterGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "EssaLab.StronglyTypedIds.Core.StronglyTypedIdAttribute";
    private const string FingerprintFullName = "EssaLab.StronglyTypedIds.Core._StronglyTypedIdsBaseGenerated";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var entityTypes = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => node is PropertyDeclarationSyntax { Type: GenericNameSyntax
            {
                Identifier.Text: "DbSet",
            }},
            transform: static (ctx, _) =>
            {
                var prop = (IPropertySymbol?)ctx.SemanticModel.GetDeclaredSymbol(ctx.Node);
                return (prop?.Type as INamedTypeSymbol)?.TypeArguments.FirstOrDefault();
            })
            .Where(static t => t is not null)
            .Select(static (t,_) => t!);
       
        var idsFromEntities =
            entityTypes.Combine(context.CompilationProvider)
                .SelectMany(static (data, _) => ExtractIds(data.Left, data.Right));
        
        var uniqueIds = idsFromEntities.Collect()
            .Select(static (all, _) => all.GroupBy(x => x.Key).Select(g => g.First()).ToImmutableArray());
        
        var hasEfCore =
            context.CompilationProvider.Select(static (c, _) =>
                c.ReferencedAssemblyNames.Any(a => a.Name == "Microsoft.EntityFrameworkCore"));

        context.RegisterSourceOutput(
            uniqueIds.Combine(hasEfCore),
            (spc, data) =>
            {
                var (ids, hasEf) = data;
                
                if (ids.IsDefaultOrEmpty)
                    return;

                if (!hasEf)
                {
                    spc.ReportDiagnostic(
                        Diagnostic.Create(
                            new DiagnosticDescriptor(
                                "STID003",
                                "EF Core Missing",
                                "Please add a reference to Microsoft.EntityFrameworkCore.",
                                "Setup",
                                DiagnosticSeverity.Error,
                                true),
                            Location.None));
                }
                
                GenerateExtensionClass(spc, ids);
                foreach (var id in ids)
                    GenerateStandaloneConverter(spc, id);
            });

        
    }

    private static IEnumerable<IdEfData> ExtractIds(
        ITypeSymbol entity,
        Compilation compilation)
    {
        var attr = compilation.GetTypeByMetadataName(AttributeFullName);
        var fingerprint = compilation.GetTypeByMetadataName(FingerprintFullName);

        if (attr is null || fingerprint is null)
            yield break;

        foreach (var prop in entity.GetMembers().OfType<IPropertySymbol>())
        {
            if (prop.Type is not INamedTypeSymbol propType)
                continue;

            var attrData = propType.GetAttributes()
                .FirstOrDefault(a =>
                    SymbolEqualityComparer.Default.Equals(a.AttributeClass, attr));

            if (attrData is null)
                continue;

            yield return new IdEfData(
                new IdKey(
                    propType.Name,
                    propType.ContainingNamespace.IsGlobalNamespace
                        ? null
                        : propType.ContainingNamespace.ToDisplayString()),
                GetBackingTypeStatic(attrData));
        }
    }


    private static string GetBackingTypeStatic(AttributeData attrData)
    {
        if (attrData.ConstructorArguments.Length == 0)
            return "Guid";

        var val = attrData.ConstructorArguments[0].Value;

        var i = val switch
        {
            int x => x,
            _ => (int)val!
        };

        return i switch
        {
            1 => "int",
            2 => "long",
            _ => "Guid"
        };
    }
    
    private static void GenerateExtensionClass(SourceProductionContext spc, ImmutableArray<IdEfData> ids)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine("namespace  EssaLab.StronglyTypedIds.Convertors.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine("public static class StronglyTypedIdEfExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static void AddStronglyTypedIdConventions(this ModelConfigurationBuilder configurationBuilder)");
        sb.AppendLine("    {");
        foreach (var id in ids)
        {
            sb.AppendLine($"        configurationBuilder.Properties<{id.Key.Namespace}.{id.Key.Name}>().HaveConversion<{id.Key.Namespace}.{id.Key.Name}EfConverter>();");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        spc.AddSource("StronglyTypedIdEfExtensions.g.cs", sb.ToString());
    }

    private static void GenerateStandaloneConverter(SourceProductionContext spc, IdEfData data)
    {
         var sb = new StringBuilder();
         var converterName = $"{data.Key.Name}EfConverter";
         sb.AppendLine("// <auto-generated/>");
         sb.AppendLine("using Microsoft.EntityFrameworkCore.Storage.ValueConversion;");
         sb.AppendLine();
         sb.AppendLine($"namespace {data.Key.Namespace ?? "EssaLab.StronglyTypedIds.Convertors.EntityFrameworkCore"};");
         sb.AppendLine();
         sb.AppendLine($"internal sealed class {converterName} : ValueConverter<{data.Key.Name}, {data.BackingType}>");
         sb.AppendLine("{");
         sb.AppendLine($"    public {converterName}() : base(");
         sb.AppendLine($"        id => id.Value,");
         sb.AppendLine($"        value => new {data.Key.Name}(value))");
         sb.AppendLine("    { }");
         sb.AppendLine("}");
         
         spc.AddSource($"{data.Key.Name}.EfConverter.g.cs", sb.ToString());
    }
}

