using System.Collections.Generic;
using System.Linq;
using System.Text;
using EssaLab.StronglyTypedIds.Convertors.EFCore.Common.Diagnostics;
using EssaLab.StronglyTypedIds.Convertors.EFCore.Common.Models;
using EssaLab.StronglyTypedIds.Shared;
using EssaLab.StronglyTypedIds.Shared.Helpers;
using Microsoft.CodeAnalysis;
namespace EssaLab.StronglyTypedIds.Convertors.EFCore;

/// <summary>
/// Incremental source generator for EF Core Value Converters for strongly-typed IDs.
/// </summary>
[Generator]
public sealed class EfConverterGenerator : IIncrementalGenerator
{
    private const string EfCoreNameSpace = "Microsoft.EntityFrameworkCore";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var hasEfCore = context.CompilationProvider.Select(static (compilation, _) => 
            compilation.ReferencedAssemblyNames.Any(a => a.Name == EfCoreNameSpace)
        );

        var idsFromCompilation = context.CompilationProvider
            .Select(static (compilation, _) =>
            {
                var extracted = IdExtractor.ExtractIdsFromCompilation(compilation);
                
                var distinct = extracted
                    .Select(d => new IdEfData(new IdKey(d.Name, d.Namespace), d.BackingType))
                    .Distinct()
                    .ToArray();
                    
                return new EquatableArray<IdEfData>(distinct);
            });

        // 5. مرحلة التوليد (Generation)
        context.RegisterSourceOutput(idsFromCompilation.Combine(hasEfCore), static (spc, data) =>
    {
        var (ids, hasEf) = data;

        if (ids.Count == 0) return;

        if (!hasEf)
        {
            spc.ReportDiagnostic(Diagnostic.Create(EfConverterDiagnostics.EfCoreMissing, Location.None));
            return;
        }

        GenerateExtensionClass(spc, ids);
        foreach (var id in ids)
        {
            GenerateStandaloneConverter(spc, id);
        }
    });
}

    

    private static void GenerateExtensionClass(SourceProductionContext spc, EquatableArray<IdEfData> ids)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Extension methods for registering strongly-typed ID converters in EF Core.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class StronglyTypedIdEfExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Configures all identified strongly-typed IDs to use their corresponding value converters.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static void AddStronglyTypedIdConventions(this ModelConfigurationBuilder configurationBuilder)");
        sb.AppendLine("    {");
        foreach (var id in ids)
        {
            sb.AppendLine($"        configurationBuilder.Properties<{(id.Key.Namespace is null ? "" : id.Key.Namespace + ".")}{id.Key.Name}>().HaveConversion<{(id.Key.Namespace is null ? "" : id.Key.Namespace + ".")}{id.Key.Name}EfConverter>();");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        spc.AddSource("StronglyTypedIdEfExtensions.g.cs", sb.ToString());
    }

    private static void GenerateStandaloneConverter(SourceProductionContext spc, IdEfData data)
    {
        var sb = new StringBuilder();
        var converterName = $"{data.Key.Name}EfConverter";
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.EntityFrameworkCore.Storage.ValueConversion;");
        sb.AppendLine();
        sb.AppendLine($"namespace {data.Key.Namespace ?? "EssaLab.StronglyTypedIds.Convertors.EntityFrameworkCore"};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// EF Core ValueConverter for <see cref=\"{(data.Key.Namespace is null ? "" : data.Key.Namespace + ".")}{data.Key.Name}\"/>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"internal sealed class {converterName} : ValueConverter<{data.Key.Name}, {data.BackingType}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public {converterName}() : base(");
        sb.AppendLine($"        static id => id.Value,");
        sb.AppendLine($"        static value => new {data.Key.Name}(value))");
        sb.AppendLine("    { }");
        sb.AppendLine("}");

        spc.AddSource($"{(data.Key.Namespace is null ? "" : data.Key.Namespace + ".")}{data.Key.Name}.EfConverter.g.cs", sb.ToString());
    }
}
