using System;
using EssaLab.StronglyTypedIds.Core.Common.Models;

namespace EssaLab.StronglyTypedIds.Core.Templates;

internal static class TemplatesRepository
{
    private const string CommonHeader = """
        // <auto-generated/>
        #nullable enable
        using System;

        namespace {Namespace};

    """;

    private const string GuidTemplate = CommonHeader + """
        /// <summary>
        /// Represents a strongly-typed ID for <see cref="{Name}"/>.
        /// </summary>
        public partial record struct {Name}(Guid Value) : IComparable<{Name}>, IEquatable<{Name}>
        {
            public static {Name} Empty => new(Guid.Empty);
            public static {Name} New() => new(Guid.NewGuid());

            public override string ToString() => Value.ToString();
            public int CompareTo({Name} other) => Value.CompareTo(other.Value);
            public bool Equals({Name} other) => Value.Equals(other.Value);
            public override int GetHashCode() => Value.GetHashCode();

            public static implicit operator Guid({Name} id) => id.Value;
            public static explicit operator {Name}(Guid value) => new(value);
        }
    """;

    private const string IntTemplate = CommonHeader + """
        public partial record struct {Name}(int Value) : IComparable<{Name}>, IEquatable<{Name}>
        {
            public static {Name} Empty => new(0);

            public override string ToString() => Value.ToString();
            public int CompareTo({Name} other) => Value.CompareTo(other.Value);
            public bool Equals({Name} other) => Value.Equals(other.Value);
            public override int GetHashCode() => Value.GetHashCode();

            public static implicit operator int({Name} id) => id.Value;
            public static explicit operator {Name}(int value) => new(value);
        }
    """;
    
    private const string LongTemplate = CommonHeader + """
        public partial record struct {Name}(long Value) : IComparable<{Name}>, IEquatable<{Name}>
        {
            public static {Name} Empty => new(0L);
            public override string ToString() => Value.ToString();
            public int CompareTo({Name} other) => Value.CompareTo(other.Value);
            public bool Equals({Name} other) => Value.Equals(other.Value);
            public override int GetHashCode() => Value.GetHashCode();
            public static implicit operator long({Name} id) => id.Value;
            public static explicit operator {Name}(long value) => new(value);
        }
    """;

    private const string StringTemplate = CommonHeader + """
        public partial record struct {Name}(string Value) : IComparable<{Name}>, IEquatable<{Name}>
        {
            public static {Name} Empty => new(string.Empty);
            public override string ToString() => Value ?? string.Empty;
            public int CompareTo({Name} other) => string.Compare(Value, other.Value, StringComparison.Ordinal);
            public bool Equals({Name} other) => Value == other.Value;
            public override int GetHashCode() => Value?.GetHashCode() ?? 0;
            public static implicit operator string({Name} id) => id.Value;
            public static explicit operator {Name}(string value) => new(value);
        }
    """;

    private const string DecimalTemplate = CommonHeader + """
        public partial record struct {Name}(decimal Value) : IComparable<{Name}>, IEquatable<{Name}>
        {
            public static {Name} Empty => new(0m);
            public override string ToString() => Value.ToString();
            public int CompareTo({Name} other) => Value.CompareTo(other.Value);
            public bool Equals({Name} other) => Value.Equals(other.Value);
            public override int GetHashCode() => Value.GetHashCode();
            public static implicit operator decimal({Name} id) => id.Value;
            public static explicit operator {Name}(decimal value) => new(value);
        }
    """;


    internal static string? GetCodeForGenerated(IdRecordData data)
    {
        // 1. اختار التيمبلت الخام بناءً على النوع
        var rawTemplate = data.BackingType switch
        {
            "Guid"    => GuidTemplate,
            "int"     => IntTemplate,
            "long"    => LongTemplate,
            "string"  => StringTemplate,
            "decimal" => DecimalTemplate,
            _      => null
        };

        if (rawTemplate is null) return null;
        
        // 2. احقن كل الـ data جوه التيمبلت
        return rawTemplate
        .Replace("{Name}", data.Name)
        .Replace("{Namespace}", data.Namespace ?? "Global")
        .Replace("{BackingType}", data.BackingType);

    }
}