using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EssaLab.StronglyTypedIds.Convertors.Json;

[Generator]
public sealed class JsonConverterGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "EssaLab.StronglyTypedIds.Core.StronglyTypedIdAttribute";
    private const string FingerprintFullName = "EssaLab.StronglyTypedIds.Core._StronglyTypedIdsBaseGenerated";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
      var usedTypeSymbols =
             context.SyntaxProvider
                 .CreateSyntaxProvider(
                     static (node, _) => node is IdentifierNameSyntax,
                     static (ctx, _) =>
                     {
                         var symbol = ctx.SemanticModel.GetSymbolInfo(ctx.Node).Symbol;
                         return symbol as INamedTypeSymbol;
                     })
                 .Where(static s => s is not null)
                 .Select(static (s, _) => s!)
                 .Collect();
         
         var idTypes =
             usedTypeSymbols.Combine(context.CompilationProvider)
                 .Select((data, _) =>
                 {
                     var (types, compilation) = data;
      
                     var attr = compilation.GetTypeByMetadataName(AttributeFullName);
                     var fingerprint = compilation.GetTypeByMetadataName(FingerprintFullName);
      
                     if (attr is null || fingerprint is null)
                         return ImmutableArray<IdJsonData>.Empty;
      
                     var result = new List<IdJsonData>();
      
                     foreach (var type in types.Distinct(SymbolEqualityComparer.Default))
                     {
                         if (type.ContainingAssembly is not IAssemblySymbol asm)
                             continue;
      
                         // هل هذا assembly فيه fingerprint؟
                         var hasFp = asm.GetAttributes()
                             .Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, fingerprint));
      
                         if (!hasFp) continue;
      
                         var attrData = type.GetAttributes()
                             .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attr));
      
                         if (attrData is null) continue;
      
                         var backing = GetBackingType(attrData);
      
                         result.Add(new IdJsonData(
                             type.Name,
                             type.ContainingNamespace.ToDisplayString(),
                             backing));
                     }
      
                     return result.ToImmutableArray();
                 });
         
         var hasJsonLibrary =
             context.CompilationProvider.Select((c, _) =>
                 c.ReferencedAssemblyNames.Any(a => a.Name == "System.Text.Json"));
      
         var pipeline = idTypes.Combine(hasJsonLibrary);
      
         context.RegisterSourceOutput(pipeline, (spc, data) =>
         {
             var ids = data.Left;
             var hasJson = data.Right;
      
             if (ids.IsDefaultOrEmpty)
                 return;
      
             if (!hasJson)
             {
                 spc.ReportDiagnostic(Diagnostic.Create(
                     new DiagnosticDescriptor("STID002", "System.Text.Json Missing", "Add System.Text.Json reference.",
                         "Setup", DiagnosticSeverity.Error, true),
                     Location.None));
                 return;
             }
      
             GenerateExtensionClass(spc, ids);
      
             foreach (var id in ids)
                 GenerateStandaloneConverter(spc, id);
         });  
    }

    private string GetBackingType(AttributeData attrData)
    {
        if (attrData.ConstructorArguments.Length == 0)
            return "Guid";

        var val = attrData.ConstructorArguments[0].Value;

        var i = val switch
        {
            int x => x,
            _ => (int)val!
        };

        return i switch
        {
            1 => "int",
            2 => "long",
            _ => "Guid"
        };
    }
    
    private static void GenerateExtensionClass(SourceProductionContext spc, ImmutableArray<IdJsonData> ids)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("namespace EssaLab.StronglyTypedIds.Convertors.Json;");
        sb.AppendLine();
        sb.AppendLine("public static class StronglyTypedIdJsonExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static void AddStronglyTypedIdConverters(this JsonSerializerOptions options)");
        sb.AppendLine("    {");
        foreach (var id in ids)
        {
            sb.AppendLine($"        options.Converters.Add(new {id.Namespace}.{id.Name}JsonConverter());");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        spc.AddSource("StronglyTypedIdJsonExtensions.g.cs", sb.ToString());
    }

    private static void GenerateStandaloneConverter(SourceProductionContext spc, IdJsonData data)
    {
         // نفس كود التوليد الذي كتبناه سابقاً تماماً
         // ...
         var sb = new StringBuilder();
         var converterName = $"{data.Name}JsonConverter";
         sb.AppendLine($"// <auto-generated/>");
         sb.AppendLine($"using System;");
         sb.AppendLine($"using System.Text.Json;");
         sb.AppendLine($"using System.Text.Json.Serialization;");
         sb.AppendLine();
         sb.AppendLine($"namespace {data.Namespace ?? " EssaLab.StronglyTypedIds.Convertors.Json"};"); // استخدم namespace الـ ID الأصلي
         sb.AppendLine();
         sb.AppendLine($"internal sealed class {converterName} : JsonConverter<{data.Name}>");
         sb.AppendLine($"{{");
         // ... Read Method ...
         sb.AppendLine($"    public override {data.Name} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
         sb.AppendLine($"    {{");
         if(data.BackingType == "Guid") sb.AppendLine($"        return new {data.Name}(reader.GetGuid());");
         else if(data.BackingType == "int") sb.AppendLine($"        return new {data.Name}(reader.GetInt32());");
         else sb.AppendLine($"        return new {data.Name}(reader.GetInt64());");
         sb.AppendLine($"    }}");
         // ... Write Method ...
         sb.AppendLine($"    public override void Write(Utf8JsonWriter writer, {data.Name} value, JsonSerializerOptions options)");
         sb.AppendLine($"    {{");
         if(data.BackingType == "Guid") sb.AppendLine($"        writer.WriteStringValue(value.Value);");
         else sb.AppendLine($"        writer.WriteNumberValue(value.Value);");
         sb.AppendLine($"    }}");
         sb.AppendLine($"}}");
         
         spc.AddSource($"{data.Name}.JsonConverter.g.cs", sb.ToString());
    }
}

internal record struct IdJsonData(string Name, string? Namespace, string BackingType);