using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using EssaLab.StronglyTypedIds.Convertors.Json.Common.Diagnostics;
using EssaLab.StronglyTypedIds.Convertors.Json.Common.Models;
using EssaLab.StronglyTypedIds.Shared;
using EssaLab.StronglyTypedIds.Shared.Helpers;
using EssaLab.StronglyTypedIds.Shared.Templates;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EssaLab.StronglyTypedIds.Convertors.Json;

/// <summary>
/// Incremental source generator for System.Text.Json converters for strongly-typed IDs.
/// </summary>
[Generator]
public sealed class JsonConverterGenerator : IIncrementalGenerator
{
    private const string SystemTextJsonTargetNamespace = "System.Text.Json";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var idsFromCompilation = context.CompilationProvider
            .Select(static (compilation, _) =>
            {
                var extracted = IdExtractor.ExtractIdsFromCompilation(compilation);
                
                var distinct = extracted
                    .Select(d => new IdJsonData(d.Name, d.Namespace, d.BackingType))
                    .Distinct()
                    .ToArray();
                    
                return new EquatableArray<IdJsonData>(distinct);
            });

        var hasJsonLibrary = context.CompilationProvider.Select(static (c, _) =>
            c.ReferencedAssemblyNames.Any(a => a.Name == SystemTextJsonTargetNamespace));

        var pipeline = idsFromCompilation.Combine(hasJsonLibrary);

        context.RegisterSourceOutput(pipeline, static (spc, data) =>
        {
            var ids = data.Left;
            var hasJson = data.Right;

            if (ids.Count == 0)
                return;

            if (!hasJson)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    JsonConverterDiagnostics.JsonLibraryMissing,
                    Location.None));
                return;
            }

            GenerateExtensionClass(spc, ids);

            foreach (var id in ids)
            {
                GenerateStandaloneConverter(spc, id);
            }
        });
    }

    private static void GenerateExtensionClass(SourceProductionContext spc, EquatableArray<IdJsonData> ids)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("namespace System.Text.Json;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Extension methods for registering strongly-typed ID JSON converters.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class StronglyTypedIdJsonExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Adds converters for all identified strongly-typed IDs to the <see cref=\"JsonSerializerOptions\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static void AddStronglyTypedIdConverters(this JsonSerializerOptions options)");
        sb.AppendLine("    {");
        foreach (var id in ids)
        {
            sb.AppendLine($"        options.Converters.Add(new {(id.Namespace is null ? "" : id.Namespace + ".")}{id.Name}JsonConverter());");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        spc.AddSource("StronglyTypedIdJsonExtensions.g.cs", sb.ToString());
    }

    private static void GenerateStandaloneConverter(SourceProductionContext spc, IdJsonData data)
    {
        var template = TemplateProvider.GetTemplate(data.BackingType);
        if (template is null) return;
        var code = template.GenerateJsonCode(data.Name, data.Namespace ?? "EssaLab.StronglyTypedIds.Convertors.Json");
        spc.AddSource($"{(data.Namespace is null ? "" : data.Namespace + ".")}{data.Name}.JsonConverter.g.cs", code);
    }
}