using System.Text;
using EssaLab.StronglyTypedIds.Gens.Base.Constants;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EssaLab.StronglyTypedIds.Gens.Base.Generators;

[Generator]
internal sealed class StronglyTypedIdAttributeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(BaseConstants.StronglyTypedIdAttributeFileName,SourceText.From(StronglyTypedIdAttributeGeneratedCode(), Encoding.UTF8));
        });
    }

    private static string StronglyTypedIdAttributeGeneratedCode()
    {
        return """
                   // <auto-generated/>
                   using System;

                   namespace StronglyTypedIds;

                   /// <summary>
                   /// Strongly Typed ID
                   /// </summary>
                   public enum IdType
                   {
                       Guid,
                       Int,
                       Long
                   }

                   [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
                   public sealed class StronglyTypedIdAttribute : Attribute
                   {
                       public IdType BackingType { get; }

                       public StronglyTypedIdAttribute(IdType backingType = IdType.Guid)
                       {
                           BackingType = backingType;
                       }
                   }
               """;
    }
}