using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using EssaLab.StronglyTypedIds.Gens.EFConvertors.Common.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EssaLab.StronglyTypedIds.Gens.EFConvertors;

[Generator]
public sealed class EfConverterGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "StronglyTypedIds.StronglyTypedIdAttribute";
    private const string FingerprintFullName = "StronglyTypedIds._StronglyTypedIdsBaseGenerated";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var entityTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is PropertyDeclarationSyntax { Type: GenericNameSyntax g } && g.Identifier.Text == "DbSet",
                static (ctx, _) =>
                {
                    var propertySymbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as IPropertySymbol;
                    if (propertySymbol?.Type is INamedTypeSymbol namedType && namedType.TypeArguments.Length > 0)
                    {
                        return namedType.TypeArguments[0] as INamedTypeSymbol;
                    }
                    return null;
                })
            .Where(static s => s is not null)
            .Select(static (s, _) => s!);
    
        
        var idTypes = entityTypes.Combine(context.CompilationProvider)
            .SelectMany(static (data, _) => 
            {
                var (entityType, compilation) = data;
                var attrSymbol = compilation.GetTypeByMetadataName(AttributeFullName);
                var fingerprint = compilation.GetTypeByMetadataName(FingerprintFullName);

                if (attrSymbol is null || fingerprint is null) 
                    return [];

                var idsInEntity = new List<IdEfData>();

                foreach (var prop in entityType.GetMembers().OfType<IPropertySymbol>())
                {
                    if (prop.Type is INamedTypeSymbol propType)
                    {
                        var attrData = propType.GetAttributes()
                            .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attrSymbol));

                        if (attrData != null)
                        {
                            var backingType = GetBackingTypeStatic(attrData); 
                    
                            idsInEntity.Add(new IdEfData(
                                propType.Name,
                                propType.ContainingNamespace?.IsGlobalNamespace == true ? null : propType.ContainingNamespace?.ToDisplayString(),
                                backingType));
                        }
                    }
                }
                return idsInEntity;
            })
            .Collect()
            .Select(static (allIds, _) => allIds.Distinct().ToImmutableArray());
    
        
        var hasEfCore = context.CompilationProvider.Select((c, _) =>
            c.ReferencedAssemblyNames.Any(a => a.Name == "Microsoft.EntityFrameworkCore"));
    
        
        var pipeline = idTypes.Combine(hasEfCore);
        context.RegisterSourceOutput(pipeline, (spc, data) =>
        {
            var (ids, hasEf) = data;
            if (ids.IsDefaultOrEmpty) return;
    
            if (!hasEf)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("STID003", "EF Core Missing", "Please add a reference to Microsoft.EntityFrameworkCore.", "Setup", DiagnosticSeverity.Error, true),
                    Location.None));
                return;
            }
    
            GenerateExtensionClass(spc, ids);
            foreach (var id in ids) GenerateStandaloneConverter(spc, id);
        });
    }
    
    private static string GetBackingTypeStatic(AttributeData attrData)
    {
        if (attrData.ConstructorArguments.Length == 0)
            return "Guid";

        var val = attrData.ConstructorArguments[0].Value;

        var i = val switch
        {
            int x => x,
            _ => (int)val!
        };

        return i switch
        {
            1 => "int",
            2 => "long",
            _ => "Guid"
        };
    }
    
    private static void GenerateExtensionClass(SourceProductionContext spc, ImmutableArray<IdEfData> ids)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine("namespace StronglyTypedIds.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine("public static class StronglyTypedIdEfExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static void AddStronglyTypedIdConventions(this ModelConfigurationBuilder configurationBuilder)");
        sb.AppendLine("    {");
        foreach (var id in ids)
        {
            sb.AppendLine($"        configurationBuilder.Properties<{id.Namespace}.{id.Name}>().HaveConversion<{id.Namespace}.{id.Name}EfConverter>();");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        spc.AddSource("StronglyTypedIdEfExtensions.g.cs", sb.ToString());
    }

    private static void GenerateStandaloneConverter(SourceProductionContext spc, IdEfData data)
    {
         var sb = new StringBuilder();
         var converterName = $"{data.Name}EfConverter";
         sb.AppendLine("// <auto-generated/>");
         sb.AppendLine("using Microsoft.EntityFrameworkCore.Storage.ValueConversion;");
         sb.AppendLine();
         sb.AppendLine($"namespace {data.Namespace};");
         sb.AppendLine();
         sb.AppendLine($"internal sealed class {converterName} : ValueConverter<{data.Name}, {data.BackingType}>");
         sb.AppendLine("{");
         sb.AppendLine($"    public {converterName}() : base(");
         sb.AppendLine($"        id => id.Value,");
         sb.AppendLine($"        value => new {data.Name}(value))");
         sb.AppendLine("    { }");
         sb.AppendLine("}");
         
         spc.AddSource($"{data.Name}.EfConverter.g.cs", sb.ToString());
    }
}

