using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace EssaLab.StronglyTypedIds.Gens.EFConvertors;

[Generator]
public sealed class EfConverterGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "StronglyTypedIds.StronglyTypedIdAttribute";
    private const string FingerprintFullName = "StronglyTypedIds._StronglyTypedIdsBaseGenerated";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. مزود للكشف عن وجود EntityFrameworkCore
        var hasEfCore = context.CompilationProvider.Select(static (compilation, _) =>
            compilation.ReferencedAssemblyNames.Any(ai => ai.Name.Equals("Microsoft.EntityFrameworkCore", StringComparison.OrdinalIgnoreCase)));

        // 2. المزود الرئيسي: فحص الـ Compilation بالكامل لاستخراج الـ IDs من المراجع
        var idsFromReferences = context.CompilationProvider.Select(static (compilation, _) =>
        {
            var foundIds = new List<IdEfData>();
            
            var idAttrSymbol = compilation.GetTypeByMetadataName(AttributeFullName);
            var fingerprintSymbol = compilation.GetTypeByMetadataName(FingerprintFullName);

            if (idAttrSymbol is null || fingerprintSymbol is null)
                return (HasBase: false, Ids: ImmutableArray<IdEfData>.Empty);

            foreach (var reference in compilation.SourceModule.ReferencedAssemblySymbols)
            {
                var hasFingerprint = reference.GetAttributes().Any(attr => 
                    SymbolEqualityComparer.Default.Equals(attr.AttributeClass, fingerprintSymbol));

                if (!hasFingerprint) continue;

                GetIdsFromNamespace(reference.GlobalNamespace, idAttrSymbol, foundIds);
            }

            return (HasBase: true, Ids: foundIds.ToImmutableArray());
        });

        // 3. تجميع البيانات
        var combined = idsFromReferences.Combine(hasEfCore);

        context.RegisterSourceOutput(combined, static (spc, source) =>
        {
            var ids = source.Left.Ids;
            var hasEfLib = source.Right;
            var hasBaseInRefs = source.Left.HasBase;

            if (ids.IsDefaultOrEmpty) return;

            // Diagnostics
            if (!hasEfLib)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("STID003", "EF Core Missing", "Please add a reference to Microsoft.EntityFrameworkCore to use EF converters.", "Setup", DiagnosticSeverity.Error, true),
                    Location.None));
                return;
            }

            // 4. التوليد
            GenerateExtensionClass(spc, ids);
            
            foreach (var id in ids)
            {
                GenerateStandaloneConverter(spc, id);
            }
        });
    }

    private static void GetIdsFromNamespace(INamespaceSymbol namespaceSymbol, INamedTypeSymbol idAttrSymbol, List<IdEfData> results)
    {
        foreach (var typeSymbol in namespaceSymbol.GetTypeMembers())
        {
            var attrData = typeSymbol.GetAttributes().FirstOrDefault(attr => 
                SymbolEqualityComparer.Default.Equals(attr.AttributeClass, idAttrSymbol));

            if (attrData is not null)
            {
                int typeIndex = 0;
                if (attrData.ConstructorArguments.Length > 0 && attrData.ConstructorArguments[0].Value is int val)
                {
                    typeIndex = val;
                }
                else if (attrData.ConstructorArguments.Length > 0 && attrData.ConstructorArguments[0].Value is object enumVal)
                {
                    typeIndex = (int)enumVal;
                }

                string backingType = typeIndex switch { 1 => "int", 2 => "long", _ => "Guid" };
                results.Add(new IdEfData(typeSymbol.Name, typeSymbol.ContainingNamespace.ToDisplayString(), backingType));
            }
        }

        foreach (var childNamespace in namespaceSymbol.GetNamespaceMembers())
        {
            GetIdsFromNamespace(childNamespace, idAttrSymbol, results);
        }
    }

    private static void GenerateExtensionClass(SourceProductionContext spc, ImmutableArray<IdEfData> ids)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine("namespace StronglyTypedIds.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine("public static class StronglyTypedIdEfExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static void AddStronglyTypedIdConventions(this ModelConfigurationBuilder configurationBuilder)");
        sb.AppendLine("    {");
        foreach (var id in ids)
        {
            sb.AppendLine($"        configurationBuilder.Properties<{id.Namespace}.{id.Name}>().HaveConversion<{id.Namespace}.{id.Name}EfConverter>();");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
        spc.AddSource("StronglyTypedIdEfExtensions.g.cs", sb.ToString());
    }

    private static void GenerateStandaloneConverter(SourceProductionContext spc, IdEfData data)
    {
         var sb = new StringBuilder();
         var converterName = $"{data.Name}EfConverter";
         sb.AppendLine("// <auto-generated/>");
         sb.AppendLine("using Microsoft.EntityFrameworkCore.Storage.ValueConversion;");
         sb.AppendLine();
         sb.AppendLine($"namespace {data.Namespace};");
         sb.AppendLine();
         sb.AppendLine($"internal sealed class {converterName} : ValueConverter<{data.Name}, {data.BackingType}>");
         sb.AppendLine("{");
         sb.AppendLine($"    public {converterName}() : base(");
         sb.AppendLine($"        id => id.Value,");
         sb.AppendLine($"        value => new {data.Name}(value))");
         sb.AppendLine("    { }");
         sb.AppendLine("}");
         
         spc.AddSource($"{data.Name}.EfConverter.g.cs", sb.ToString());
    }
}

internal record struct IdEfData(string Name, string? Namespace, string BackingType);