using System.Linq;
using System.Text;
using EssaLab.StronglyTypedIds.Core.Constants;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EssaLab.StronglyTypedIds.Core.Generators;

[Generator]
public sealed class FingerprintGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var hasAnyStronglyTypedId = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                BaseConstants.StronglyTypedIdAttributeName,
                predicate: static (node, _) => node is RecordDeclarationSyntax,
                transform: static (ctx, _) => true)
            .Collect()
            .Select(static (items, _) => items.Any());
        
        
        context.RegisterSourceOutput(hasAnyStronglyTypedId, static (spc, hasAny) =>
        {
            if(!hasAny) return;
            spc.AddSource(BaseConstants.StronglyTypedIdsFingerprintFileName,SourceText.From(FingerprintGeneratedCode(),Encoding.UTF8));
        });
    }
    private static string FingerprintGeneratedCode()
    {
        return """
                      // <auto-generated/>
                      using System;
                      [assembly: StronglyTypedIds._StronglyTypedIdsBaseGenerated]
                      
                      namespace StronglyTypedIds;
                      [AttributeUsage(AttributeTargets.Assembly)]
                      public sealed class _StronglyTypedIdsBaseGenerated : Attribute 
                      {
                      }
               """;
    }
}