using System.Text;
using EssaLab.StronglyTypedIds.Core.Common.Constants;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EssaLab.StronglyTypedIds.Core.Generators;

/// <summary>
/// Incremental source generator for the [StronglyTypedId] attribute.
/// </summary>
[Generator]
public sealed class StronglyTypedIdAttributeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(BaseConstants.StronglyTypedIdAttributeFileName, SourceText.From(StronglyTypedIdAttributeGeneratedCode(), Encoding.UTF8));
        });
    }

    private static string StronglyTypedIdAttributeGeneratedCode()
    {
        return """
            // <auto-generated/>
            #nullable enable
            using System;
            
            namespace EssaLab.StronglyTypedIds;
            /// <summary>
            /// Marks a record as a strongly-typed ID.
            /// </summary>
            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
            public sealed class StronglyTypedIdAttribute<T> : Attribute 
                where T : notnull 
            {
            }
        """;
    }
}