using System.Text;
using EssaLab.StronglyTypedIds.Core.Constants;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EssaLab.StronglyTypedIds.Core.Generators;

/// <summary>
/// Incremental source generator for the [StronglyTypedId] attribute.
/// </summary>
[Generator]
internal sealed class StronglyTypedIdAttributeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource(BaseConstants.StronglyTypedIdAttributeFileName, SourceText.From(StronglyTypedIdAttributeGeneratedCode(), Encoding.UTF8));
        });
    }

    private static string StronglyTypedIdAttributeGeneratedCode()
    {
        return """
               // <auto-generated/>
               #nullable enable
               using System;

               namespace EssaLab.StronglyTypedIds.Core;

               /// <summary>
               /// Specifies the underlying type for the strongly-typed ID.
               /// </summary>
               public enum IdType
               {
                   /// <summary>Guid-based ID (default).</summary>
                   Guid,
                   /// <summary>Integer-based ID.</summary>
                   Int,
                   /// <summary>Long-based ID.</summary>
                   Long
               }

               /// <summary>
               /// Marks a record as a strongly-typed ID.
               /// </summary>
               [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
               public sealed class StronglyTypedIdAttribute : Attribute
               {
                   /// <summary>
                   /// Gets the backing type for the ID.
                   /// </summary>
                   public IdType BackingType { get; }

                   /// <summary>
                   /// Initializes a new instance of the <see cref="StronglyTypedIdAttribute"/> class.
                   /// </summary>
                   /// <param name="backingType">The underlying type for the ID. Defaults to <see cref="IdType.Guid"/>.</param>
                   public StronglyTypedIdAttribute(IdType backingType = IdType.Guid)
                   {
                       BackingType = backingType;
                   }
               }
               """;
    }
}