using System.Linq;
using System.Text;
using EssaLab.StronglyTypedIds.Core.Constants;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EssaLab.StronglyTypedIds.Core.Generators;

[Generator]
public sealed class StronglyTypedIdGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var ids = context.SyntaxProvider.ForAttributeWithMetadataName(
           BaseConstants.StronglyTypedIdAttributeName,
            predicate: static (node, _) => node is RecordDeclarationSyntax,
            transform: static (ctx, _) => 
            {
                var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
                var attribute = ctx.Attributes.First();
                
                var typeIndex = attribute.ConstructorArguments.Length > 0 
                    ? (int)attribute.ConstructorArguments[0].Value! 
                    : 0;
                
                var typeName = typeIndex switch
                {
                    1 => "int",
                    2 => "long",
                    _ => "Guid"
                };
                
                return new IdRecordData(
                    symbol.Name,
                    symbol.ContainingNamespace.IsGlobalNamespace ? null : symbol.ContainingNamespace.ToDisplayString(),
                    typeName
                );
            });
        
        context.RegisterSourceOutput(ids, static (spc, data) =>
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine();
            
            if (data.Namespace is not null)
            {
                sb.AppendLine($"namespace {data.Namespace};");
                sb.AppendLine();
            }
            
            AddStronglyTypedId(sb, data);
            spc.AddSource($"{data.Name}.StronglyTypedId.g.cs", sb.ToString());
        });
    }

    private static void AddStronglyTypedId(StringBuilder sb, IdRecordData data)
    {
        var name = data.Name;
        var type = data.BackingType;
        bool isGuid = type == "Guid";

        sb.AppendLine($"public partial record {name} : IComparable<{name}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public {type} Value {{ get; init; }}");
        sb.AppendLine();
    
        // Constructor
        sb.AppendLine($"    public {name}({type} value) => Value = value;");
        sb.AppendLine();

        sb.AppendLine(isGuid
            ? $"    public static {name} New() => new(Guid.NewGuid());"
            : $"    public static {name} Empty => new(0);");

        sb.AppendLine();
        sb.AppendLine("    public override string ToString() => Value.ToString();");
        sb.AppendLine();

        sb.AppendLine($"    public int CompareTo({name}? other)");
        sb.AppendLine(isGuid 
            ? $"        => Value.CompareTo(other?.Value ?? Guid.Empty);" 
            : $"        => Value.CompareTo(other?.Value ?? 0);");

        sb.AppendLine();

        // Operators
        sb.AppendLine($"    public static implicit operator {type}({name} id) => id.Value;");
        sb.AppendLine($"    public static explicit operator {name}({type} value) => new(value);");
        sb.AppendLine("}");
    }
    
}

internal record struct IdRecordData(string Name, string? Namespace, string BackingType);