namespace EssaLab.StronglyTypedIds.Shared.Templates.Types;

public sealed class DecimalTemplate : ITypeTemplate
{
    public string BackingType => "decimal";

    public string GenerateCoreCode(string name, string ns) => $$"""
// <auto-generated/>
#nullable enable
using System;

namespace {{ns}};

/// <summary>
/// Represents a strongly-typed ID for <see cref="{{name}}"/>.
/// </summary>
#if NET7_0_OR_GREATER
public partial record struct {{name}}(decimal Value) : IComparable<{{name}}>, IEquatable<{{name}}>, IParsable<{{name}}>
#else
public partial record struct {{name}}(decimal Value) : IComparable<{{name}}>, IEquatable<{{name}}>
#endif
{
    public static {{name}} Empty => new(0m);

    public override string ToString() => Value.ToString();
    public int CompareTo({{name}} other) => Value.CompareTo(other.Value);
    public bool Equals({{name}} other) => Value.Equals(other.Value);
    public override int GetHashCode() => Value.GetHashCode();

    public static implicit operator decimal({{name}} id) => id.Value;
    public static explicit operator {{name}}(decimal value) => new(value);

#if NET7_0_OR_GREATER    
    public static {{name}} Parse(string s, IFormatProvider? provider) => new(decimal.Parse(s, provider));
    public static bool TryParse([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? s, IFormatProvider? provider, [System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out {{name}} result)
#else
    public static {{name}} Parse(string s, IFormatProvider? provider) => new(decimal.Parse(s));
    public static bool TryParse(string? s, IFormatProvider? provider, out {{name}} result)
#endif
    {
#if NET7_0_OR_GREATER
        if (decimal.TryParse(s, provider, out var parsedValue))
#else
        if (decimal.TryParse(s, out var parsedValue))
#endif
        {
            result = new(parsedValue);
            return true;
        }
        result = default;
        return false;
    }

    public static {{name}} Parse(string s) => Parse(s, null);
    public static bool TryParse(string? s, out {{name}} result) => TryParse(s, null, out result);
}
""";

    public string GenerateEfCoreCode(string name, string ns) => $$"""
// <auto-generated/>
#nullable enable
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace {{ns}};

/// <summary>
/// EF Core ValueConverter for <see cref="{{name}}"/>.
/// </summary>
internal sealed class {{name}}EfConverter : ValueConverter<{{name}}, decimal>
{
    public {{name}}EfConverter() : base(
        static id => id.Value,
        static value => new {{name}}(value))
    { }
}
""";

    public string GenerateJsonCode(string name, string ns) => $$"""
// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace {{ns}};

/// <summary>
/// JSON converter for <see cref="{{name}}"/>.
/// </summary>
internal sealed class {{name}}JsonConverter : JsonConverter<{{name}}>
{
    public override {{name}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return new {{name}}(reader.GetDecimal());
    }

    public override void Write(Utf8JsonWriter writer, {{name}} value, JsonSerializerOptions options)
    {
        writer.WriteNumberValue(value.Value);
    }
}
""";
}
