namespace EssaLab.StronglyTypedIds.Shared.Templates.Types;

public sealed class GuidTemplate : ITypeTemplate
{
    public string BackingType => "Guid";

    public string GenerateCoreCode(string name, string ns, bool isValueType)
    {
        var recordType = isValueType ? "record struct" : "record";
        var nullableToken = isValueType ? "" : "?";
        return $$"""
                 // <auto-generated/>
                 #nullable enable
                 using System;

                 namespace {{ns}};

                 /// <summary>
                 /// Represents a strongly-typed ID for <see cref="{{name}}"/>.
                 /// </summary>
                 #if NET7_0_OR_GREATER
                 public partial {{recordType}} {{name}}(Guid Value) : IComparable<{{name}}>, IEquatable<{{name}}>, IParsable<{{name}}>
                 #else
                 public partial {{recordType}} {{name}}(Guid Value) : IComparable<{{name}}>, IEquatable<{{name}}>
                 #endif
                 {
                     public static {{name}} Empty => new(Guid.Empty);
                     public static {{name}} New() => new(Guid.NewGuid());

                     public override string ToString() => Value.ToString();

                     public int CompareTo({{name}}{{nullableToken}} other) 
                     {
                         {{(isValueType 
                             ? "return Value.CompareTo(other.Value);" 
                             : "if (ReferenceEquals(this, other)) return 0;\n        if (other is null) return 1;\n        return Value.CompareTo(other.Value);")}}
                     }

                     public {{(isValueType ? "readonly" : "virtual")}} bool Equals({{name}}{{nullableToken}} other) 
                     {
                         {{(isValueType 
                             ? "return Value.Equals(other.Value);" 
                             : "if (other is null) return false;\n        if (ReferenceEquals(this, other)) return true;\n        return Value.Equals(other.Value);")}}
                     }

                     public override int GetHashCode() => Value.GetHashCode();

                     public static implicit operator Guid({{name}} id) => id.Value;
                     public static explicit operator {{name}}(Guid value) => new(value);

                 #if NET7_0_OR_GREATER    
                     public static {{name}} Parse(string s, IFormatProvider? provider) => new(Guid.Parse(s, provider));
                     public static bool TryParse([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? s, IFormatProvider? provider, [System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out {{name}} result)
                 #else
                     public static {{name}} Parse(string s, IFormatProvider? provider) => new(Guid.Parse(s));
                     public static bool TryParse(string? s, IFormatProvider? provider, out {{name}} result)
                 #endif
                     {
                         if (Guid.TryParse(s, out var parsedValue))
                         {
                             result = new(parsedValue);
                             return true;
                         }
                         result = default{{(isValueType ? "" : "!")}}; 
                         return false;
                     }

                     public static {{name}} Parse(string s) => Parse(s, null);
                     public static bool TryParse(string? s, out {{name}} result) => TryParse(s, null, out result);
                 }
                 """;
    }

    public string GenerateEfCoreCode(string name, string ns) => $$"""
                                                                  // <auto-generated/>
                                                                  #nullable enable
                                                                  using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

                                                                  namespace {{ns}};

                                                                  /// <summary>
                                                                  /// EF Core ValueConverter for <see cref="{{name}}"/>.
                                                                  /// </summary>
                                                                  public sealed class {{name}}EfConverter : ValueConverter<{{name}}, Guid>
                                                                  {
                                                                      public {{name}}EfConverter() : base(
                                                                          static id => id.Value,
                                                                          static value => new {{name}}(value))
                                                                      { }
                                                                  }
                                                                  """;

    public string GenerateJsonCode(string name, string ns) => $$"""
// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace {{ns}};

/// <summary>
/// JSON converter for <see cref="{{name}}"/>.
/// </summary>
public sealed class {{name}}JsonConverter : JsonConverter<{{name}}>
{
    public override {{name}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return new {{name}}(reader.GetGuid());
    }

    public override void Write(Utf8JsonWriter writer, {{name}} value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.Value);
    }
}
""";
}
