namespace EssaLab.StronglyTypedIds.Shared.Templates.Types;

public sealed class IntTemplate : ITypeTemplate
{
    public string BackingType => "int";

    public string GenerateCoreCode(string name, string ns, bool isValueType)
    {
        var recordType = isValueType ? "record struct" : "record";
        var nullableToken = isValueType ? "" : "?";
        return $$"""
                  // <auto-generated/>
                  #nullable enable
                  using System;

                  namespace {{ns}};

                  /// <summary>
                  /// Represents a strongly-typed ID for <see cref="{{name}}"/>.
                  /// </summary>
                  #if NET7_0_OR_GREATER
                  public partial {{recordType}} {{name}}(int Value) : IComparable<{{name}}>, IEquatable<{{name}}>, IParsable<{{name}}>
                  #else
                  public partial {{recordType}} {{name}}(int Value) : IComparable<{{name}}>, IEquatable<{{name}}>
                  #endif
                  {
                      public static {{name}} Empty => new(0);

                      public override string ToString() => Value.ToString();
                      
                      public int CompareTo({{name}}{{nullableToken}} other) 
                      {
                          {{(isValueType 
                              ? "return Value.CompareTo(other.Value);" 
                              : "if (ReferenceEquals(this, other)) return 0;\n        if (other is null) return 1;\n        return Value.CompareTo(other.Value);")}}
                      }

                      public {{(isValueType ? "readonly" : "virtual")}} bool Equals({{name}}{{nullableToken}} other) 
                      {
                          {{(isValueType 
                              ? "return Value.Equals(other.Value);" 
                              : "if (other is null) return false;\n        if (ReferenceEquals(this, other)) return true;\n        return Value.Equals(other.Value);")}}
                      }

                      public override int GetHashCode() => Value.GetHashCode();

                      public static implicit operator int({{name}} id) => id.Value;
                      public static explicit operator {{name}}(int value) => new(value);

                  #if NET7_0_OR_GREATER    
                      public static {{name}} Parse(string s, IFormatProvider? provider) => new(int.Parse(s, provider));
                      public static bool TryParse([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? s, IFormatProvider? provider, [System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out {{name}} result)
                  #else
                      public static {{name}} Parse(string s, IFormatProvider? provider) => new(int.Parse(s));
                      public static bool TryParse(string? s, IFormatProvider? provider, out {{name}} result)
                  #endif
                      {
                  #if NET7_0_OR_GREATER
                          if (int.TryParse(s, provider, out var parsedValue))
                  #else
                          if (int.TryParse(s, out var parsedValue))
                  #endif
                          {
                              result = new(parsedValue);
                              return true;
                          }
                          result = default{{(isValueType ? "" : "!")}}; 
                          return false;
                      }

                      public static {{name}} Parse(string s) => Parse(s, null);
                      public static bool TryParse(string? s, out {{name}} result) => TryParse(s, null, out result);
                  }
                  """;
    }

    public string GenerateEfCoreCode(string name, string ns) => $$"""
// <auto-generated/>
#nullable enable
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace {{ns}};

/// <summary>
/// EF Core ValueConverter for <see cref="{{name}}"/>.
/// </summary>
internal sealed class {{name}}EfConverter : ValueConverter<{{name}}, int>
{
    public {{name}}EfConverter() : base(
        static id => id.Value,
        static value => new {{name}}(value))
    { }
}
""";

    public string GenerateJsonCode(string name, string ns) => $$"""
// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace {{ns}};

/// <summary>
/// JSON converter for <see cref="{{name}}"/>.
/// </summary>
internal sealed class {{name}}JsonConverter : JsonConverter<{{name}}>
{
    public override {{name}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return new {{name}}(reader.GetInt32());
    }

    public override void Write(Utf8JsonWriter writer, {{name}} value, JsonSerializerOptions options)
    {
        writer.WriteNumberValue(value.Value);
    }
}
""";
}
