namespace EssaLab.StronglyTypedIds.Shared.Templates.Types;

public sealed class LongTemplate : ITypeTemplate
{
    public string BackingType => "long";

    public string GenerateCoreCode(string name, string ns) => $$"""
// <auto-generated/>
#nullable enable
using System;

namespace {{ns}};

/// <summary>
/// Represents a strongly-typed ID for <see cref="{{name}}"/>.
/// </summary>
public partial record struct {{name}}(long Value) : IComparable<{{name}}>, IEquatable<{{name}}>
{
    public static {{name}} Empty => new(0L);

    public override string ToString() => Value.ToString();
    public int CompareTo({{name}} other) => Value.CompareTo(other.Value);
    public bool Equals({{name}} other) => Value.Equals(other.Value);
    public override int GetHashCode() => Value.GetHashCode();

    public static implicit operator long({{name}} id) => id.Value;
    public static explicit operator {{name}}(long value) => new(value);
}
""";

    public string GenerateEfCoreCode(string name, string ns) => $$"""
// <auto-generated/>
#nullable enable
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace {{ns}};

/// <summary>
/// EF Core ValueConverter for <see cref="{{name}}"/>.
/// </summary>
internal sealed class {{name}}EfConverter : ValueConverter<{{name}}, long>
{
    public {{name}}EfConverter() : base(
        static id => id.Value,
        static value => new {{name}}(value))
    { }
}
""";

    public string GenerateJsonCode(string name, string ns) => $$"""
// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace {{ns}};

/// <summary>
/// JSON converter for <see cref="{{name}}"/>.
/// </summary>
internal sealed class {{name}}JsonConverter : JsonConverter<{{name}}>
{
    public override {{name}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return new {{name}}(reader.GetInt64());
    }

    public override void Write(Utf8JsonWriter writer, {{name}} value, JsonSerializerOptions options)
    {
        writer.WriteNumberValue(value.Value);
    }
}
""";
}
