namespace EssaLab.StronglyTypedIds.Shared.Templates.Types;

public sealed class StringTemplate : ITypeTemplate
{
    public string BackingType => "string";

    public string GenerateCoreCode(string name, string ns, bool isValueType)
    {
        var recordType = isValueType ? "record struct" : "record";
        var nullableToken = isValueType ? "" : "?";
        return $$"""
                  // <auto-generated/>
                  #nullable enable
                  using System;

                  namespace {{ns}};

                  /// <summary>
                  /// Represents a strongly-typed ID for <see cref="{{name}}"/>.
                  /// </summary>
                  #if NET7_0_OR_GREATER
                  public partial {{recordType}} {{name}}(string Value) : IComparable<{{name}}>, IEquatable<{{name}}>, IParsable<{{name}}>
                  #else
                  public partial {{recordType}} {{name}}(string Value) : IComparable<{{name}}>, IEquatable<{{name}}>
                  #endif
                  {
                      public static {{name}} Empty => new(string.Empty);

                      public override string ToString() => Value ?? string.Empty;
                      
                      public int CompareTo({{name}}{{nullableToken}} other) 
                      {
                          {{(isValueType 
                              ? "return string.Compare(Value, other.Value, StringComparison.Ordinal);" 
                              : "if (ReferenceEquals(this, other)) return 0;\n        if (other is null) return 1;\n        return string.Compare(Value, other.Value, StringComparison.Ordinal);")}}
                      }

                      public {{(isValueType ? "readonly" : "virtual")}} bool Equals({{name}}{{nullableToken}} other) 
                      {
                          {{(isValueType 
                              ? "return Value == other.Value;" 
                              : "if (other is null) return false;\n        if (ReferenceEquals(this, other)) return true;\n        return Value == other.Value;")}}
                      }

                      public override int GetHashCode() => Value?.GetHashCode() ?? 0;

                      public static implicit operator string({{name}} id) => id.Value;
                      public static explicit operator {{name}}(string value) => new(value);

                  #if NET7_0_OR_GREATER    
                      public static {{name}} Parse(string s, IFormatProvider? provider) => new(s);
                      public static bool TryParse([System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? s, IFormatProvider? provider, [System.Diagnostics.CodeAnalysis.MaybeNullWhen(false)] out {{name}} result)
                  #else
                      public static {{name}} Parse(string s, IFormatProvider? provider) => new(s);
                      public static bool TryParse(string? s, IFormatProvider? provider, out {{name}} result)
                  #endif
                      {
                          if (s is null)
                          {
                              result = default{{(isValueType ? "" : "!")}}; 
                              return false;
                          }
                          result = new(s);
                          return true;
                      }

                      public static {{name}} Parse(string s) => Parse(s, null);
                      public static bool TryParse(string? s, out {{name}} result) => TryParse(s, null, out result);
                  }
                  """;
    }

    public string GenerateEfCoreCode(string name, string ns) => $$"""
// <auto-generated/>
#nullable enable
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace {{ns}};

/// <summary>
/// EF Core ValueConverter for <see cref="{{name}}"/>.
/// </summary>
public sealed class {{name}}EfConverter : ValueConverter<{{name}}, string>
{
    public {{name}}EfConverter() : base(
        static id => id.Value,
        static value => new {{name}}(value))
    { }
}
""";

    public string GenerateJsonCode(string name, string ns) => $$"""
// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace {{ns}};

/// <summary>
/// JSON converter for <see cref="{{name}}"/>.
/// </summary>
public sealed class {{name}}JsonConverter : JsonConverter<{{name}}>
{
    public override {{name}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return new {{name}}(reader.GetString() ?? string.Empty);
    }

    public override void Write(Utf8JsonWriter writer, {{name}} value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.Value);
    }
}
""";
}
