namespace EssaLab.StronglyTypedIds.Shared.Templates.Types;

public sealed class StringTemplate : ITypeTemplate
{
    public string BackingType => "string";

    public string GenerateCoreCode(string name, string ns) => $$"""
// <auto-generated/>
#nullable enable
using System;

namespace {{ns}};

/// <summary>
/// Represents a strongly-typed ID for <see cref="{{name}}"/>.
/// </summary>
public partial record struct {{name}}(string Value) : IComparable<{{name}}>, IEquatable<{{name}}>
{
    public static {{name}} Empty => new(string.Empty);

    public override string ToString() => Value ?? string.Empty;
    public int CompareTo({{name}} other) => string.Compare(Value, other.Value, StringComparison.Ordinal);
    public bool Equals({{name}} other) => Value == other.Value;
    public override int GetHashCode() => Value?.GetHashCode() ?? 0;

    public static implicit operator string({{name}} id) => id.Value;
    public static explicit operator {{name}}(string value) => new(value);
}
""";

    public string GenerateEfCoreCode(string name, string ns) => $$"""
// <auto-generated/>
#nullable enable
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace {{ns}};

/// <summary>
/// EF Core ValueConverter for <see cref="{{name}}"/>.
/// </summary>
internal sealed class {{name}}EfConverter : ValueConverter<{{name}}, string>
{
    public {{name}}EfConverter() : base(
        static id => id.Value,
        static value => new {{name}}(value))
    { }
}
""";

    public string GenerateJsonCode(string name, string ns) => $$"""
// <auto-generated/>
#nullable enable
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace {{ns}};

/// <summary>
/// JSON converter for <see cref="{{name}}"/>.
/// </summary>
internal sealed class {{name}}JsonConverter : JsonConverter<{{name}}>
{
    public override {{name}} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return new {{name}}(reader.GetString() ?? string.Empty);
    }

    public override void Write(Utf8JsonWriter writer, {{name}} value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value.Value);
    }
}
""";
}
